### ISSUE TITLE
scrolling in chat is really weird 

### ISSUE THREAD

**Issue by fellnerse** [SpiritFour/whatsanalyze#162]
should not snap on desktop
on mobile it should not be possible to scroll the website when scrolling in this thing
also after scrolled outside of chat, i can scroll the chat when im scrolling outsided -> can not scroll website

**Comment by mowolf** [comment]
I don't think that. I like the current scrolling. 

> also after scrolled outside of chat, i can scroll the chat when im scrolling outsided -> can not scroll website

I just tried on my iPhone and I could not reproduce that
