### ISSUE TITLE
fix gtags

### ISSUE THREAD

**Issue by fellnerse** [SpiritFour/whatsanalyze#169]
- [x] some gtags have wrong labels (the other way around)
- [x] add more gtags to everything
- [x] wiki how to use gtags (https://github.com/SpiritFour/best-chat-analyzer/wiki/Google-Analytics)

**Comment by fellnerse** [comment]
@Adrian-Thiesen is this done?

**Comment by mowolf** [comment]
@Adrian-Thiesen the PR is still open but this issue is now set "Done"?
