### ISSUE TITLE
Fix wordcloud bugs for german market

### ISSUE THREAD

**Issue by PKehnel** [SpiritFour/whatsanalyze#184]
Create example chat with audio, video, ... and see what attachments are not filtered.
e.g <media omitted ...

Maybe we can just remove all messages, that have an attachment, but then how to handle messages with attachment and message

**Comment by fellnerse** [comment]
reddit: `Wenn ich den Chat ohne Medien exportiere steht in der der Word Cloud am meisten benutzt "<Medien Ausgeschlossen>"`

**Comment by mowolf** [comment]
See  #236
