### ISSUE TITLE
Add Github/Open-Source reference on Website for social proof

### ISSUE THREAD

**Issue by themihel** [SpiritFour/whatsanalyze#210]
Found your project on reddit and it's an interesting idea.
However, if you didn't mention the Open-Source part in the Post, I wouldn't know it exists. As an idea you could add some information about Open-Source (e.g. FAQ) or just a Github link to your website to get some sort of social proof (at least for developers).

Vice versa you could link the website in the repo itself, in case someone finds it by accident on Github and wants to check it out in the wild.

(Relates partially to #173)

**Comment by mowolf** [comment]
Thanks @themihel :) We will add this.

**Comment by mowolf** [comment]
See #217
