### ISSUE TITLE
Add system messages to filter them out (like <media omitted ...) 

### ISSUE THREAD

**Issue by fellnerse** [SpiritFour/whatsanalyze#236]
system message? how do we handle stuff like this?

**Comment by mowolf** [comment]
We need the exact line and add it to:
https://github.com/SpiritFour/whatsanalyze/blob/67cafa50b77143e605bf342f1a6f04f712825fd2/functions/transformChatData.js#L408

**Comment by mowolf** [comment]
We should create a wiki entry for this and write it in the readme

**Comment by mowolf** [comment]
reddit: Wenn ich den Chat ohne Medien exportiere steht in der der Word Cloud am meisten benutzt "<Medien Ausgeschlossen>"

Create example chat with audio, video, ... and see what attachments are not filtered.
e.g <media omitted ...

**Comment by fellnerse** [comment]
@mowolf can you link here the lines from your repository?
@PKehnel do you want to do this? as you already had some prs handling this
from reddit: "<Medien ausgeschlossen>"
