### ISSUE TITLE
Downloading PDF results in error

### ISSUE THREAD

**Issue by fellnerse** [SpiritFour/whatsanalyze#253]
<img width="511" alt="image" src="https://user-images.githubusercontent.com/41167496/111040691-8b969700-8434-11eb-992c-4e228a3c866e.png">
 used the groupchat of adrian
i think an image is missing as attachment; should never fail i would argue

**Comment by PKehnel** [comment]
can reproduce with the ARC M.... Chat, this is also on Master now (since I merged your pull request before reading this issue and didn't encounter the error with the chat I tested.)
