### ISSUE TITLE
`functions/transformChatData.js`

### ISSUE THREAD

**Issue by amgdbmc** [SpiritFour/whatsanalyze#320]
`functions/transformChatData.js`

line 354
replace:
```    
const minDate = new Date(Math.min.apply(null, this.dates));
const maxDate = new Date(Math.max.apply(null, this.dates));
```

with:
```
const sortedDates = this.dates.sort();
const minDate = new Date(sortedDates[0]);
const maxDate = new Date(sortedDates[-1]);
```

I created a branch, but I can't push to the repo.

I was able to process 175974 messages.

_Originally posted by @danblackadder in https://github.com/SpiritFour/whatsanalyze/issues/274#issuecomment-869063298_

**Comment by mowolf** [comment]
I have no idea what this should mean...
